.TH "AiSD::noneV" 3 "Tue Mar 15 2022" "Tablica Dynamiczna" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AiSD::noneV \- Pusta struktura\&. Varianty nie moga przyjmowac typ void\&. Alternatywnie moglem uzyc wbudowanego 'monostate'\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <TestingFunction\&.hpp>\fP
.SH "Detailed Description"
.PP 
Pusta struktura\&. Varianty nie moga przyjmowac typ void\&. Alternatywnie moglem uzyc wbudowanego 'monostate'\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Tablica Dynamiczna from the source code\&.
