.TH "include/DynamicArray.h" 3 "Thu Mar 17 2022" "Tablica Dynamiczna" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/DynamicArray.h
.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include <fstream>\fP
.br
\fC#include <sstream>\fP
.br
\fC#include <string>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBAiSD::DynamicArray\fP"
.br
.ti -1c
.RI "struct \fBRecord\fP"
.br
.RI "struktora zosta³a utworzona i próbowa³em zamiast T j¹ zast¹pic, ale coœ siê nie uda³o\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBAiSD\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBT\fP   long"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define T   long"

.SH "Author"
.PP 
Generated automatically by Doxygen for Tablica Dynamiczna from the source code\&.
