.TH "Record" 3 "Thu Mar 17 2022" "Tablica Dynamiczna" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Record \- struktora zostala utworzona i próbowalem zamiast T ja zastapic, ale cos sie nie udalo\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <DynamicArray\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "std::string \fBname\fP"
.br
.ti -1c
.RI "unsigned \fBgrade\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
struktora zostala utworzona i próbowalem zamiast T ja zastapic, ale cos sie nie udalo\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Tablica Dynamiczna from the source code\&.
